name: Go

on:
  push:
    branches: [ master, jclab-main ]
  pull_request:
    branches: [ master, jclab-main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install golint
      run: go get -u golang.org/x/lint/golint
      
    - name: Update go.sum
      run: make mod

    - name: Build
      run: make build

    - name: Test
      run: make test
