name: Publish Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install golint
      run: go get -u golang.org/x/lint/golint
      
    - name: Update go.sum
      run: make mod

    - name: Build
      run: make build

    - name: Test
      run: make test

  push_to_registry:
    name: Push Docker image to gchr.io
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Release Image Name
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        run: |
          echo "IMAGE_VERSION=release-${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
          echo "NEED_IMAGE_PUSH=true" >> $GITHUB_ENV
          echo "LATEST_IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/rdpgw:latest" >> $GITHUB_ENV
      - name: Set Taged Image Name
        if: ${{ !(github.event_name == 'release' && github.event.action == 'published') }}
        run: |
          echo "LATEST_IMAGE_NAME=" >> $GITHUB_ENV
          echo "${GITHUB_REF}" | grep "refs/tags" >/dev/null && echo "NEED_IMAGE_PUSH=true" >> $GITHUB_ENV || true
          (echo "${GITHUB_REF}" | grep "refs/tags" >/dev/null && echo "IMAGE_VERSION=tag-${GITHUB_REF#refs/*/v}" || echo "IMAGE_VERSION=commit-${GITHUB_SHA::8}") >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install golint
        run: go get -u golang.org/x/lint/golint
      - name: Update go.sum
        run: make mod
      - name: Build
        run: make build
      - name: Test
        run: make test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: ${{ env.NEED_IMAGE_PUSH == 'true' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dev/docker-distroless/Dockerfile
          push: ${{ env.NEED_IMAGE_PUSH == 'true' }}
          tags: |
            ${{ env.LATEST_IMAGE_NAME }}
            ghcr.io/${{ github.repository_owner }}/rdpgw:${{ env.IMAGE_VERSION }}
